version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:9.5
    healthcheck:
      test: "exit 0"
    environment:
      - POSTGRES_PASSWORD=''
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crypto_exchange
    volumes:
      - pgdata:/var/lib/postgresql/data/

  app:
    restart: always
    build: .
    depends_on:
      - postgres
    ports:
      - "8001:8080"
    volumes:
      - .:/code

volumes:
  redis_data:
  pgdata:
