# Generated by Django 2.0 on 2018-01-05 19:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('give', models.CharField(max_length=5)),
                ('receive', models.CharField(max_length=5)),
                ('give_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('receive_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('status', models.CharField(choices=[('new', 'new'), ('paid', 'paid'), ('received', 'received'), ('completed', 'completed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='rates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Rate'),
        ),
    ]
