# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
